### ISSUE TITLE
Disallowed record types cause submit form to think its empty

### ISSUE THREAD

**Issue by whikloj** [danloveg/NCTR-Bagit-Record-Transfer#7]
Submitting some new records (Step 7 of 7). 
I added a PDF, a DOCX and a TIFF. It informed me the Tiff was not allowed. I removed the Tiff and re-submitted and it tells me I cannot submit a form without files.

Screenshots below.
Add 3 files (*.pdf, *.docx, *.tiff)
![Screen Shot 2021-04-14 at 9 42 27 AM](https://user-images.githubusercontent.com/2857697/114729840-f70aa780-9d05-11eb-9ffa-f732bceda88f.png)

Hit **Submit**
![Screen Shot 2021-04-14 at 9 42 44 AM](https://user-images.githubusercontent.com/2857697/114729968-10135880-9d06-11eb-9b26-bc63da5d2bbf.png)

Click **OK** and remove the Tiff file
![Screen Shot 2021-04-14 at 9 43 02 AM](https://user-images.githubusercontent.com/2857697/114730068-26b9af80-9d06-11eb-9348-93024cd5ca52.png)

---
![Screen Shot 2021-04-14 at 9 43 10 AM](https://user-images.githubusercontent.com/2857697/114730141-3638f880-9d06-11eb-8257-4297c697f2a5.png)

Hit **Submit** again
![Screen Shot 2021-04-14 at 9 43 20 AM](https://user-images.githubusercontent.com/2857697/114730237-4d77e600-9d06-11eb-9b75-4d6fc2b12ff5.png)

**Comment by danloveg** [comment]
This is a JavaScript coding issue on my part, the submit button depends on there being files in the queue. If the queue is empty, it will not work. Since you hit submit and all of the files in the queue were processed, it thought the upload space was empty and therefore no files were there.

I'll address this in an upcoming fix.
